### ISSUE TITLE
Ruby Readline error

### ISSUE THREAD

**Issue by jasperrooduijn** [cantino/reckon#127]
I'm trying to run Reckon on my macbook (M2).

I have the following Ruby version installed:

```
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]
```

I get this error:

```
/Users/user-x/.gem/ruby/3.3.0/gems/highline-3.0.0/lib/highline/terminal.rb:127:in `block in readline_read': uninitialized constant HighLine::Terminal::Readline (NameError)

Readline.readline(prompt, true)
^^^^^^^^
Did you mean?  Reline
from /Users/user-x/.gem/ruby/3.3.0/gems/highline-3.0.0/lib/highline/terminal.rb:173:in `run_preserving_stty'
from /Users/user-x/.gem/ruby/3.3.0/gems/highline-3.0.0/lib/highline/terminal.rb:125:in `readline_read'
from /Users/user-x/.gem/ruby/3.3.0/gems/highline-3.0.0/lib/highline/terminal.rb:100:in `get_line_with_readline'
from /Users/user-x/.gem/ruby/3.3.0/gems/highline-3.0.0/lib/highline/terminal.rb:87:in `get_line'
from /Users/user-x/.gem/ruby/3.3.0/gems/highline-3.0.0/lib/highline.rb:542:in `get_line'
from /Users/user-x/.gem/ruby/3.3.0/gems/highline-3.0.0/lib/highline.rb:526:in `get_response_line_mode'
from /Users/user-x/.gem/ruby/3.3.0/gems/highline-3.0.0/lib/highline/question.rb:534:in `get_response'
from /Users/user-x/.gem/ruby/3.3.0/gems/highline-3.0.0/lib/highline/question.rb:546:in `get_response_or_default'
from /Users/user-x/.gem/ruby/3.3.0/gems/highline-3.0.0/lib/highline/question_asker.rb:31:in `ask_once'
from /Users/user-x/.gem/ruby/3.3.0/gems/highline-3.0.0/lib/highline.rb:223:in `ask'
from /Users/user-x/.gem/ruby/3.3.0/gems/reckon-0.9.4/lib/reckon/options.rb:176:in `parse_command_line_options'
from /Users/user-x/.gem/ruby/3.3.0/gems/reckon-0.9.4/bin/reckon:7:in `<top (required)>'
from /Users/user-x/.gem/ruby/3.3.0/bin/reckon:25:in `load'
from /Users/user-x/.gem/ruby/3.3.0/bin/reckon:25:in `<main>'
```

Not sure whats wrong. Am i using the correct Ruby version?

**Comment by s01ipsist** [comment]
This is caused by a recent release of an associated library.
https://rubygems.org/gems/highline/versions/3.0.0
Reckon is not yet compatible. I've confirmed this using multiple rubies, and rolling back to Highline 2.1.0.

You can keep using reckon in the meantime by using Bundler to pin to the old highline library.

create `Gemfile`
```
source 'https://rubygems.org'

gem 'reckon'
gem 'highline', '< 3.0'
```

run `bundle`
then use `bundle exec reckon`

**Comment by benprew** [comment]
I'll build a new version of reckon that pins highline to the 2.x branch for now. Long-term fix is to remove references to readline, but that requires more testing.

**Comment by jasperrooduijn** [comment]
Nice! Thanks for the quick fix 👍
