### ISSUE TITLE
Problem reading csv file

### ISSUE THREAD

**Issue by alexjj** [cantino/reckon#55]
Not sure if it's my CSV file but the error makes me think something else is wrong on my system:

```
I didn't find a high-likelyhood money column, but I'm taking my best guess with column 7.
/home/alex/.gem/ruby/2.2.0/gems/reckon-0.4.3/lib/reckon/money.rb:167:in `pretty_for': undefined method `strftime' for nil:NilClass (NoMethodError)
	from /home/alex/.gem/ruby/2.2.0/gems/reckon-0.4.3/lib/reckon/csv_parser.rb:43:in `pretty_date_for'
	from /home/alex/.gem/ruby/2.2.0/gems/reckon-0.4.3/lib/reckon/app.rb:212:in `block in each_row_backwards'
	from /home/alex/.gem/ruby/2.2.0/gems/reckon-0.4.3/lib/reckon/app.rb:210:in `each'
	from /home/alex/.gem/ruby/2.2.0/gems/reckon-0.4.3/lib/reckon/app.rb:210:in `each_row_backwards'
	from /home/alex/.gem/ruby/2.2.0/gems/reckon-0.4.3/lib/reckon/app.rb:201:in `block in output_table'
	from /home/alex/.gem/ruby/2.2.0/gems/terminal-table-1.5.2/lib/terminal-table/table.rb:216:in `yield_or_eval'
	from /home/alex/.gem/ruby/2.2.0/gems/terminal-table-1.5.2/lib/terminal-table/table.rb:17:in `initialize'
	from /home/alex/.gem/ruby/2.2.0/gems/reckon-0.4.3/lib/reckon/app.rb:199:in `new'
	from /home/alex/.gem/ruby/2.2.0/gems/reckon-0.4.3/lib/reckon/app.rb:199:in `output_table'
	from /home/alex/.gem/ruby/2.2.0/gems/reckon-0.4.3/bin/reckon:10:in `<top (required)>'
	from /home/alex/.gem/ruby/2.2.0/bin/reckon:23:in `load'
	from /home/alex/.gem/ruby/2.2.0/bin/reckon:23:in `<main>'
```

Let me know what else you'd like?

**Comment by BlackEdder** [comment]
It looks like it has problems pretty printing the date column. Any chance you could provide the (anonymized) csv file?

**Comment by alexjj** [comment]
Sure, here's a [link](https://www.dropbox.com/s/sfxapial8cwog8r/ExportData.csv?dl=0) to a few transactions in the CSV.

I was testing to see what reckon would do with a vanilla CSV from my bank. I've previously used YNAB and had a pandas script to convert the CSV into a better format for it (plus YNAB was very particular).

**Comment by kalafut** [comment]
@alexjj Did you use the --contains-header command line option?  I ran into the same error until I added that.

**Comment by alexjj** [comment]
Thanks that fixed it.
