### ISSUE TITLE
Problem with importing CSV

### ISSUE THREAD

**Issue by Bouke** [cantino/reckon#60]
The export from my bank (ABN NL) looks like this:

```
123456789   EUR 20160102    15,00   10,00   20160102    -5,00   DESCRIPTION
123456789   EUR 20160102    10,00   0,00    20160102    -10,00  DESCRIPTION
```

Imported as:

```
reckon -f FILE -p -c € --ignore-columns 4,5 --comma-separates-cents -v --date-format '%Y%m%d' --csv-separator '\t'
What is the account name of this bank account in Ledger? |Assets:Bank:Checking| 
I didn't find a high-likelyhood money column, but I'm taking my best guess with column 1.
/usr/local/lib/ruby/gems/2.2.0/gems/reckon-0.4.4/lib/reckon/csv_parser.rb:196:in `detect_columns': undefined method `[]' for nil:NilClass (NoMethodError)
    from /usr/local/lib/ruby/gems/2.2.0/gems/reckon-0.4.4/lib/reckon/csv_parser.rb:13:in `initialize'
    from /usr/local/lib/ruby/gems/2.2.0/gems/reckon-0.4.4/lib/reckon/app.rb:18:in `new'
    from /usr/local/lib/ruby/gems/2.2.0/gems/reckon-0.4.4/lib/reckon/app.rb:18:in `initialize'
    from /usr/local/lib/ruby/gems/2.2.0/gems/reckon-0.4.4/bin/reckon:7:in `new'
    from /usr/local/lib/ruby/gems/2.2.0/gems/reckon-0.4.4/bin/reckon:7:in `<top (required)>'
    from /usr/local/bin/reckon:23:in `load'
    from /usr/local/bin/reckon:23:in `<main>'
```

When using a real tab instead of \t, the error is this:

```
reckon -f FILE -p -c € --ignore-columns 4,5 --comma-separates-cents -v --date-format '%Y%m%d' --csv-separator ' ' 
What is the account name of this bank account in Ledger? |Assets:Bank:Checking| 
I didn't find a high-likelyhood money column, but I'm taking my best guess with column 5.
I'm having trouble parsing 123456789 with the desired format: %Y%m%d
```

**Comment by cantino** [comment]
Well, `123456789` isn't a parseable date format, right?  Or am I misunderstanding?

**Comment by cantino** [comment]
You may need to tell it which is the date column.  It looks like a real tab instead of \t is working, though.

**Comment by whirm** [comment]
In case anyone is having the same issue. (note the real tab as csv separator)
This works for me: `reckon -f TXT123412341234.TAB --comma-separates-cents -c EUR --date-format '%Y%m%d' --csv-separator '      ' -v --ignore-columns 1,2,3,4,5`
