### ISSUE TITLE
Error Importing

### ISSUE THREAD

**Issue by CestDiego** [cantino/reckon#64]
I get this when running the importing command

```
 ✘  ~/Documents/Org-Notes  reckon -f export.csv
What is the account name of this bank account in Ledger? |Assets:Bank:Checking|
I didn't find a high-likelyhood money column, but I'm taking my best guess with column 5.
/Users/dberrocal/.rvm/gems/ruby-2.3.0/gems/reckon-0.4.4/lib/reckon/money.rb:167:in `pretty_for': undefined method `strftime' for nil:NilClass (NoMethodError)
    from /Users/dberrocal/.rvm/gems/ruby-2.3.0/gems/reckon-0.4.4/lib/reckon/csv_parser.rb:43:in `pretty_date_for'
    from /Users/dberrocal/.rvm/gems/ruby-2.3.0/gems/reckon-0.4.4/lib/reckon/app.rb:237:in `block in each_row_backwards'
    from /Users/dberrocal/.rvm/gems/ruby-2.3.0/gems/reckon-0.4.4/lib/reckon/app.rb:235:in `each'
    from /Users/dberrocal/.rvm/gems/ruby-2.3.0/gems/reckon-0.4.4/lib/reckon/app.rb:235:in `each_row_backwards'
    from /Users/dberrocal/.rvm/gems/ruby-2.3.0/gems/reckon-0.4.4/lib/reckon/app.rb:97:in `walk_backwards'
    from /Users/dberrocal/.rvm/gems/ruby-2.3.0/gems/reckon-0.4.4/bin/reckon:19:in `<top (required)>'
    from /Users/dberrocal/.rvm/gems/ruby-2.3.0/bin/reckon:23:in `load'
    from /Users/dberrocal/.rvm/gems/ruby-2.3.0/bin/reckon:23:in `<main>'
    from /Users/dberrocal/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/dberrocal/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by cantino** [comment]
Hey @CestDiego. I think you'll need to tell Reckon the money column directly instead of having it guess, because I think it's guessing wrong.

**Comment by sralmai** [comment]
@CestDiego the date column is being guessed incorrectly (so `Chronic` can't parse a time from the raw entry in that column and returns `nil`, and then `nil.strfortime...` when trying to format the time).

Can you post a few lines of your sample source? (For bonus points, you could add your example data here: https://github.com/cantino/reckon/blob/master/spec/reckon/csv_parser_spec.rb#L401 and then make the tests pass :D)

**Comment by kototama** [comment]
I get the same error with this file, which a sample CSV file from the hledger documentation:

```
"Date","Note","Amount"
"2012/3/22","DEPOSIT","50.00"
"2012/3/23","TRANSFER TO SAVINGS","-10.00"
```
