### ISSUE TITLE
Missing or stray quote in line error

### ISSUE THREAD

**Issue by kototama** [cantino/reckon#71]
Hello there,

I have this error:

```
/usr/lib/ruby/2.1.0/csv.rb:1846:in `block (2 levels) in shift': Missing or stray quote in line 1 (CSV::MalformedCSVError)
	from /usr/lib/ruby/2.1.0/csv.rb:1819:in `each'
	from /usr/lib/ruby/2.1.0/csv.rb:1819:in `block in shift'
	from /usr/lib/ruby/2.1.0/csv.rb:1779:in `loop'
	from /usr/lib/ruby/2.1.0/csv.rb:1779:in `shift'
	from /usr/lib/ruby/2.1.0/csv.rb:1721:in `each'
	from /usr/lib/ruby/2.1.0/csv.rb:1735:in `to_a'
	from /usr/lib/ruby/2.1.0/csv.rb:1735:in `read'
	from /usr/lib/ruby/2.1.0/csv.rb:1293:in `parse'
	from /home/user/.gem/ruby/2.1.0/gems/reckon-0.4.4/lib/reckon/csv_parser.rb:241:in `parse'
	from /home/user/.gem/ruby/2.1.0/gems/reckon-0.4.4/lib/reckon/csv_parser.rb:11:in `initialize'
	from /home/user/.gem/ruby/2.1.0/gems/reckon-0.4.4/lib/reckon/app.rb:18:in `new'
	from /home/user/.gem/ruby/2.1.0/gems/reckon-0.4.4/lib/reckon/app.rb:18:in `initialize'
	from /home/user/.gem/ruby/2.1.0/gems/reckon-0.4.4/bin/reckon:7:in `new'
	from /home/user/.gem/ruby/2.1.0/gems/reckon-0.4.4/bin/reckon:7:in `<top (required)>'
	from /home/user/.gem/ruby/2.1.0/bin/reckon:23:in `load'
	from /home/user/.gem/ruby/2.1.0/bin/reckon:23:in `<main>'
```

When parsing this file:

```
"transactionId";"localBankCode";"localAccountNumber";"remoteBankCode";"remoteAccountNumber";"date";"valutadate";"value_value";"value_currency";"localName";"remoteName";"remoteName1";"purpose";"purpose1";"purpose2";"purpose3";"purpose4";"purpose5";"purpose6";"purpose7";"purpose8";"purpose9";"purpose10";"purpose11";"category";"category1";"category2";"category3";"category4";"category5";"category6";"category7"
"";"123456789";"123456";"111111";"22222";"2017/05/03";"2015/06/08";"-40.44";"EUR";"JOHNY CASH";"SHOP CO";"";"SOMETHING";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";"";""
```

Any idea?

**Comment by cantino** [comment]
Try setting `--csv-separator` to `;`, since this isn't a normal CSV. (CSV stands for "`comma` separated values")

**Comment by cantino** [comment]
It may be guessing the wrong date column. I really need to make that an option. You could try setting `--ignore-columns 7` and `--contains-header`

**Comment by kototama** [comment]
Eh it works! Thank you so much!

**Comment by cantino** [comment]
Yay, glad it's working!

**Comment by benprew** [comment]
This appears to have been resolved, I'm closing this issue.  Feel free to reopen it if you're still having problems.
